name: Waka Readme

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:
  
jobs:
  update-readme:
    name: Update this repo's README
    runs-on: self-hosted
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_MESSAGE: Update README Using WakaTime Data
          SHOW_TIME: false
          SHOW_TITLE: true
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
